version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "EST"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "CHORE(NPM) - "
    cooldown:
      semver-minor-days: 14
      semver-patch-days: 30
      include:
        - "@sentry/*"
        - "storybook"
        - "@storybook/*"
    groups:
      emotion:
        applies-to: version-updates
        patterns:
          - "@emotion/*"
      eslint:
        applies-to: version-updates
        patterns:
          - "eslint"
          - "eslint-*"
          - "typescript-eslint"
          - "@emotion/eslint-plugin"
          - "@eslint/*"
          - "@graphql-eslint/eslint-plugin"
        exclude-patterns:
          - "eslint-plugin-storybook"
      graphql-codegen:
        applies-to: version-updates
        patterns:
          - "@graphql-codegen/*"
      leafygreen:
        applies-to: version-updates
        patterns:
          - "@leafygreen-ui/*"
          - "@lg-chat/*"
      react:
        applies-to: version-updates
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      sentry:
        applies-to: version-updates
        patterns:
          - "@sentry/*"
      storybook:
        applies-to: version-updates
        patterns:
          - "eslint-plugin-storybook"
          - "storybook"
          - "storybook-addon-*"
          - "@storybook/*"
      testing-library:
        applies-to: version-updates
        patterns:
          - "@testing-library/*"
